# Generated by Django 5.2.6 on 2025-09-24 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="isCompleted",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
